install! 'cocoapods', deterministic_uuids: false, share_schemes_for_development_pods: false

# Supported platform.
platform :ios, '10.0'

# Use frameworks for Swift.
use_frameworks!

# Ignore the pod warnings.
inhibit_all_warnings!

target 'Tests' do
  # Linter
  pod 'SwiftLint', '~> 0.28'

  # The test frameworks
  pod 'Quick',      '~> 1.3'
  pod 'Nimble',     '~> 9.0'
  # Fix for `Ambiguous use of XCTest.tearDown` in swizzle method
  # https://github.com/kylef/Mockingjay/pull/120
  pod 'Mockingjay', :git => 'https://github.com/kylef/Mockingjay.git', :branch => 'master'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited) YES'
    end
  end
end
