# This is the minimum Fastlane version to use.
fastlane_version '2.121.0'

# Don't generate README files.
skip_docs

#############
### LANES ###
#############

lane :pr do
  # Check the code formatting.
  swiftlint(
		mode: :lint,
 		config_file: 'Example/.swiftlint.yml'
	)

  # Validate the QuickSpec to not use `fit`, `fcontext`, or `fdescribe`.
  validate_specs directories: ['Example/Tests']

  # Run the tests.
  scan(
    workspace:              'Example/Example.xcworkspace',
    scheme:                 'Tests',
    clean:                  true,
    skip_build:             true
  )
end
